In [4]:
import pandas as pd
import numpy as np

import os

# for EDA
# from ydata_profiling import ProfileReport 

%matplotlib inline
import matplotlib.pyplot as plt

In [9]:
ruta_data = "../data/Generacio_Montserratina.xlsx"  #data\Generacio_Montserratina.xlsx

df_PV = pd.read_excel(ruta_data)

df_PV.head(20)

           TAG                Time  Energia  Potència
0   FV_EACTIVA 2024-07-16 13:15:02    48876      12.0
1   FV_EACTIVA 2024-07-16 13:00:01    48873      12.0
2   FV_EACTIVA 2024-07-16 12:45:02    48870      12.0
3   FV_EACTIVA 2024-07-16 12:30:01    48867      12.0
4   FV_EACTIVA 2024-07-16 12:15:02    48864      12.0
5   FV_EACTIVA 2024-07-16 12:00:01    48861      16.0
6   FV_EACTIVA 2024-07-16 11:45:02    48857      12.0
7   FV_EACTIVA 2024-07-16 11:30:01    48854      12.0
8   FV_EACTIVA 2024-07-16 11:15:02    48851      12.0
9   FV_EACTIVA 2024-07-16 11:00:01    48848      12.0
10  FV_EACTIVA 2024-07-16 10:45:02    48845      12.0
11  FV_EACTIVA 2024-07-16 10:30:01    48842      12.0
12  FV_EACTIVA 2024-07-16 10:15:02    48839      12.0
13  FV_EACTIVA 2024-07-16 10:00:01    48836       8.0
14  FV_EACTIVA 2024-07-16 09:45:01    48834      12.0
15  FV_EACTIVA 2024-07-16 09:30:02    48831      12.0
16  FV_EACTIVA 2024-07-16 09:15:01    48828       8.0
17  FV_EACTIVA 2024-07-16 09:00:02    48826       8.0
18  FV_EACTIVA 2024-07-16 08:45:01    48824       8.0
19  FV_EACTIVA 2024-07-16 08:30:02    48822       4.0